"""added uc sport schedule user-name

Revision ID: 2cb0992ff4ab
Revises: c524415f25c1
Create Date: 2016-04-24 16:38:43.692159

"""

# revision identifiers, used by Alembic.
revision = '2cb0992ff4ab'
down_revision = 'c524415f25c1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sport_schedule_name_uc', 'sport_schedule', ['user_id', 'name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sport_schedule_name_uc', 'sport_schedule', type_='unique')
    ### end Alembic commands ###
