"""user_activity and busyness

Revision ID: 51578b5cfa93
Revises: 2cb0992ff4ab
Create Date: 2016-04-26 14:31:42.879080

"""

# revision identifiers, used by Alembic.
revision = '51578b5cfa93'
down_revision = '2cb0992ff4ab'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sport_schedule')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_schedule',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reminder_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='sport_schedule_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sport_schedule_pkey'),
    sa.UniqueConstraint('user_id', 'name', name='sport_schedule_name_uc')
    )
    op.drop_table('user_activity')
    ### end Alembic commands ###
