"""added cardio activity

Revision ID: 5c3051ef2bc1
Revises: 08d5f8697a6a
Create Date: 2016-05-12 15:54:26.436151

"""

# revision identifiers, used by Alembic.
revision = '5c3051ef2bc1'
down_revision = '08d5f8697a6a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardio_activity',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('activity_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=False), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=False), nullable=True),
    sa.Column('cardio_type', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['user_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardio_activity')
    ### end Alembic commands ###
