"""sport schedule columns

Revision ID: 66fc705e9ee7
Revises: c29fdc8588d9
Create Date: 2016-05-30 13:39:53.788753

"""

# revision identifiers, used by Alembic.
revision = '66fc705e9ee7'
down_revision = 'c29fdc8588d9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_schedule', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('sport_schedule', sa.Column('time', sa.Time(), nullable=True))
    op.add_column('sport_schedule', sa.Column('weekdays', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_schedule', 'weekdays')
    op.drop_column('sport_schedule', 'time')
    op.drop_column('sport_schedule', 'is_active')
    ### end Alembic commands ###
