"""buddies

Revision ID: 6e581314c9f8
Revises: c29fdc8588d9
Create Date: 2016-06-07 23:13:05.155113

"""

# revision identifiers, used by Alembic.
revision = '6e581314c9f8'
down_revision = 'c29fdc8588d9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy',
    sa.Column('user_1_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_2_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('buddies_since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_1_id', 'user_2_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buddy')
    ### end Alembic commands ###
