"""device revisions

Revision ID: 874dbd99db2b
Revises: 2cb0992ff4ab
Create Date: 2016-05-20 16:07:39.720057

"""

# revision identifiers, used by Alembic.
revision = '874dbd99db2b'
down_revision = '2cb0992ff4ab'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('device_address', sa.String(length=17), nullable=True),
    sa.Column('device_class', sa.String(length=100), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gym', sa.Column('MAC_address', sa.String(length=17), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gym', 'MAC_address')
    op.drop_table('device')
    ### end Alembic commands ###
