"""user activity

Revision ID: 9709a1a9a6be
Revises: 2cb0992ff4ab
Create Date: 2016-05-02 13:51:12.695931

"""

# revision identifiers, used by Alembic.
revision = '9709a1a9a6be'
down_revision = '2cb0992ff4ab'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
                    sa.Column(
                        'id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
                    sa.Column(
                        'start_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column(
                        'end_date', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activity')
    ### end Alembic commands ###
