"""user activity foreign key

Revision ID: ff8bb0abd100
Revises: 9709a1a9a6be
Create Date: 2016-05-02 14:14:42.467848

"""

# revision identifiers, used by Alembic.
revision = 'ff8bb0abd100'
down_revision = '51578b5cfa93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column(
        'user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_foreign_key(None, 'user_activity', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_activity', type_='foreignkey')
    op.drop_column('user_activity', 'user_id')
    ### end Alembic commands ###
